# Generated by Django 5.1.15 on 2026-09-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='sent_to',
            field=models.EmailField(blank=True, help_text='Delivery address when the OTP was issued (e.g. a new email pending confirmation).', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set when the one-time welcome email has been delivered.', null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Account verification'), ('reset', 'Password reset'), ('login', 'Login confirmation'), ('email_change', 'Email change')], default='verify', max_length=15),
        ),
    ]
