# Generated by Django 5.1.15 on 2026-09-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reported_professional_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_professional_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_professional_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_service',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
