# Generated by Django 5.1.15 on 2026-09-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_offer_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider')], help_text='Who made the most recent price offer during negotiation.', max_length=10),
        ),
    ]
